keys:
  - &k age16jrjr4w7lvpx54jl89hjyuznh5gx8vjv7xdx4skn006zaerympaqelvn09
  - &pk age10r2a32kynwf24egvptdk6rg88nguaw6ufhggwvj9ywfqpn8369vsx3n2f2
creation_rules:
  - path_regex: secrets/.*\.(yml|yaml)$
    key_groups:
      - age:
          - *k
  - path: home/secrets.yaml
    key_groups:
      - age:
          - *pk
