keys:
  - &pk age1244ypl8fmmv46nl7z6ma7vl4jqx872re3vvszwydrg90zkp5ngms3tl27z
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *pk
  - path_regex: secrets/.*\.json$
    key_groups:
      - age:
          - *pk
